export const serviceEndpoints = [
  { method: "GET", path: "/health", access: "health", description: "Liveness của driver-service" },
  { method: "GET", path: "/ready", access: "internal", description: "Readiness và trạng thái dependency" },
  { method: "GET", path: "/endpoints", access: "metadata", description: "Danh mục endpoint của service" },
  { method: "GET", path: "/drivers/:id", access: "public", roles: ["CUSTOMER", "DRIVER(owner)", "ADMIN"], description: "Lấy hồ sơ tài xế" },
  { method: "GET", path: "/drivers/nearby", access: "public", roles: ["CUSTOMER", "ADMIN"], description: "Tìm tài xế online theo tọa độ, bán kính và phân trang" },
  { method: "POST", path: "/drivers/otp/request", access: "public", roles: ["PUBLIC"], description: "Yêu cầu OTP đăng ký tài xế" },
  { method: "POST", path: "/drivers/otp/verify", access: "public", roles: ["PUBLIC"], description: "Xác minh OTP và cấp registration token" },
  { method: "POST", path: "/drivers/register", access: "public", roles: ["DRIVER registration token"], idempotent: true, description: "Nộp hồ sơ tài xế" },
  { method: "GET", path: "/drivers/me/application", access: "public", roles: ["DRIVER"], description: "Xem trạng thái hồ sơ của tài xế hiện tại" },
  { method: "PUT", path: "/drivers/me/availability", access: "public", roles: ["DRIVER"], description: "Bật hoặc tắt nhận chuyến" },
  { method: "PUT", path: "/drivers/me/location", access: "public", roles: ["DRIVER"], description: "Cập nhật vị trí tài xế" },
  { method: "GET", path: "/admin/drivers", access: "public", roles: ["ADMIN"], description: "Liệt kê hồ sơ tài xế" },
  { method: "GET", path: "/admin/drivers/:id", access: "public", roles: ["ADMIN"], description: "Xem chi tiết hồ sơ tài xế" },
  { method: "POST", path: "/admin/drivers/:id/approve", access: "public", roles: ["ADMIN"], description: "Duyệt hồ sơ tài xế" },
  { method: "POST", path: "/admin/drivers/:id/reject", access: "public", roles: ["ADMIN"], description: "Từ chối hồ sơ tài xế" },
  { method: "GET", path: "/internal/drivers/nearby", access: "internal", description: "Tìm ứng viên cho booking-service" },
  { method: "POST", path: "/internal/drivers/:id/status", access: "internal", description: "Giữ hoặc giải phóng trạng thái tài xế" },
];
